# .github/workflows/system-repair.yml  (in TRS-System-Health-Check-Setup)
name: 🧩 TRS Auto-Repair Chain
on:
  workflow_run:
    workflows: ["🩺 TRS System Health Monitor"]
    types:
      - completed

jobs:
  trigger-repair:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: 📡 Dispatch Sentinel Repair
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "TRS Sentinel Auto-Fix"
          repo: TRSAlliance/sentinel
          token: ${{ secrets.TRIGGER_TOKEN }}
